### ISSUE TITLE
While multiplying using brackets, It shows invalid

### ISSUE THREAD

**Issue by webricated** [harsh98trivedi/Simple-JavaScript-Calculator#4]
10(2)= 20 ------>Needed
10(2)=PLEASE INPUT VALID EXPRESSION

**Comment by webricated** [comment]
![Screenshot_2022-05-14-13-41-28-71_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/105015109/168417298-268f067b-f626-4d84-a56c-b1031e287498.jpg)

**Comment by mnaray** [comment]
I fixed this specific issue in PR #5 
However, there's no possibility to use bracket multiplication twice yet.

For example:

2(5(2)) = PLEASE INPUT VALID EXPRESSION ---> current

instead of

2(5(2)) = 20 ---> correct

You can probably fix this with the method I created, just gotta get a bit more in depth.

**Comment by harsh98trivedi** [comment]
Thanks, @mnaray! However, it doesn't seem to be working on keypress event(s). Kindly create a new PR or I will try to fix that later.

**Comment by harsh98trivedi** [comment]
Thanks, @mnaray for fixing the issue!

**Comment by mnaray** [comment]
You're welcome. Lmk if you meed help with something else!
